#!/usr/bin/env bash
#Displays numbers from 1-20 then prints the text as instructed in the numbers shown
i=1
while ((i < 21))
do
	echo $i
	case "$i" in
		4) echo "bad luck from China";;
		9) echo "bad luck from Japan";;
		17) echo "bad luck from Italy";;
		esac
	((i++))
done
